version: "3.9"
    
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database

volumes:
  db_volume: